const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const { zodToJsonSchema } = require("zod-to-json-schema");
const puppeteer = require("puppeteer");


const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_API_KEY,
})

const interviewReportSchema = z.object({
    matchScore: z.number().min(0).max(100).describe("The match score between the candidate and the job description, ranging from 0 to 100"),
    technicalQuestions: z.array(z.object({
        question: z.string().describe("The technical questions can be asked in the interview"),
        intention: z.string().describe("The intention of the interviewer behind asking the technical question"),
        answer: z.string().describe("How to answer this question, what points to cover, what approach to take etc.")
    })).describe("Technical questions that can be asked in the interview along with their intention and how to answer them"),
    behavioralQuestions: z.array(z.object({
        question: z.string().describe("The behavioral questions can be asked in the interview"),
        intention: z.string().describe("The intention of the interviewer behind asking the behavioral question"),
        answer: z.string().describe("How to answer this question, what points to cover, what approach to take etc.")
    })).describe("Behavioral questions that can be asked in the interview along with their intention and how to answer them"),
    skillGaps: z.array(z.object({
        skill: z.string().describe("The skill that the candidate is lacking or needs improvement in"),
        severity: z.enum(['low', 'medium', 'high']).describe("The severity of the skill gap, whether it is low, medium or high")
    })).describe("Skill gaps identified in the candidate"),
    preparationPlan: z.array(z.object({
        day: z.number().describe("The day of the preparation plan, starting from 1"),
        focus: z.string().describe("The focus of the preparation plan for that day"),
        tasks: z.array(z.string()).describe("The tasks to be completed on that day")
    })).describe("Preparation plan for the candidate to improve their skills and prepare for the interview"),
    title: z.string().describe("The title of the job for which the interview report is generated"),
})

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {

    const prompt = `Generate an interview report for the candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}`

    const response = await ai.models.generateContent({
        model: "gemini-3.6-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(interviewReportSchema)
        }
    })


    return JSON.parse(response.text)
}


async function generateResumePDF({resume, selfDescription, jobDescription}) {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

    const pdfBuffer = await page.pdf({ format: 'A4', margin:{
        top: "10mm",
        bottom: "10mm",
        left: "10mm",
        right: "10mm"
    }  });

    await browser.close()

    return pdfBuffer;
}



async function generateResumePDF({resume, selfDescription, jobDescription}) {
    const resumePdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
    })

    const prompt = `Generate a resume PDF for a candidate with the following details:
                    Resume: ${resume}
                    Self Description: ${selfDescription}
                    Job Description: ${jobDescription}
                    The output should be in HTML format which can be converted to PDF using any library like puppeteer.
                    The resume should be tailored for the given job description and should highlight the candidate's strenghts and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visual appealing.
                    The contennt of the resume should be not sound like it's generated by AI and should be as close as possible to real human-written resume.
                    You can highlight the content using some colors or the different font styles but the overall design should be simple and professional.
                    The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                    The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description. 
                    `

    const response = await ai.models.generateContent({
        model: "gemini-3.6-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(resumePdfSchema)
        }
    })


    const jsonContent = JSON.parse(response.text)

    const pdfBuffer = await generateResumePDF(jsonContent.html)

    return pdfBuffer
}


module.exports = {
    generateInterviewReport,
    generateResumePDF
}